# Generated by Django 4.2.6 on 2023-10-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=500)),
                ('timedate', models.DateField(blank=True)),
            ],
        ),
    ]
