# Generated by Django 4.2.6 on 2023-10-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcomment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timedate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
