# Generated by Django 4.2.6 on 2023-10-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_timedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timedate',
            field=models.DateField(blank=True),
        ),
    ]
